financas_pessoais/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('register/', include('register.urls'))
]

register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('new/', views.new, name='new')
]

users/urls.py
from django.urls import path

from . import views
from .profiles import profile_views


app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.detail, name='detail'),

    path('me/accounts/create', views.create_account, name='create_account'),
    path('me/accounts', views.list_accounts, name='list_accounts'),

    path('me/transactions/create', views.create_transaction, name='create_transaction'),
    path('me/transactions', views.list_transactions, name='list_transactions'),

    path('profile/', profile_views.show_profile, name='show_profile')
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class Account(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    balance = models.FloatField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tb_accounts'

class Transaction(models.Model):
    debit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='debit_account')
    credit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='credit_account')
    value = models.FloatField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'tb_transactions'

register/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField()

    class Meta:
        db_table = 'tb_profile'

accounts/views.py
from django.shortcuts import render

register/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

def new(request):
    if request.method == 'GET':
        return render(request, 'register/new.html')
    elif request.method == 'POST':

        post_data = request.POST

        u = User(
            username=post_data.get('txtUsername'),
            email=post_data.get('txtEmail'),
            first_name=post_data.get('txtFirstName'),
            last_name=post_data.get('txtLastName')
        )

        u.set_password(post_data.get("txtPassword"))
        u.save()

        return render(request, 'register/success.html')

users/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from accounts.models import Account, Transaction


def index(request):

    if request.user.is_authenticated:

        total_num_accounts = request.user.account_set.all().count()
        total_num_transactions = Transaction.objects.filter(debit_account__user_id=request.user).count()

        context = {
        'total_num_accounts': total_num_accounts,
        'total_num_transactions': total_num_transactions
        }

        return render(request, 'users/index.html', context=context)

    else:

        return render(request, 'users/index.html')


def detail(request: HttpRequest, user_id: int):

    return render(request, 'users/detail.html')


def create_account(request):

    if request.method == 'GET':
        return render(request, 'accounts/create.html')

    elif request.method == 'POST':

        post_data = request.POST

        if len(post_data.get("txtInitialBalance").strip()):
            balance = float(post_data.get("txtInitialBalance").strip())

        else:
            balance = 0

        account = Account(
            user_id=request.user,
            name=post_data.get('txtAccountName'),
            balance=balance
        )

        account.save()

        return HttpResponseRedirect(reverse('users:list_accounts',))


def list_accounts(request):

    user_accounts = request.user.account_set.all()

    context = {
        'user_accounts': user_accounts
    }

    return render(request, 'accounts/list.html', context=context)


def create_transaction(request):
    if request.method == 'GET':
        all_user_accounts = request.user.account_set.all()

        context = {
            'all_user_accounts': all_user_accounts
        }

        return render(request, 'transactions/create.html', context=context)

    elif request.method == 'POST':

        debit_account_id = request.POST['menuDebitAccount']
        credit_account_id = request.POST['menuCreditAccount']
        value = float(request.POST['txtValue'])

        debit_account = Account.objects.get(pk=debit_account_id)
        credit_account = Account.objects.get(pk=credit_account_id)

        transaction = Transaction(
            debit_account=debit_account,
            credit_account=credit_account,
            value=value
        )

        transaction.save()

        debit_account.balance = debit_account.balance - value
        credit_account.balance = credit_account.balance + value

        debit_account.save()
        credit_account.save()

        return HttpResponseRedirect(reverse('users:index', ))

def list_transactions(request):

    transactions = Transaction.objects.filter(debit_account__user_id=request.user).all()

    context = {
        'transactions': transactions
    }

    return render(request, 'transactions/index.html', context=context)

register/templates/register/new.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 480px">
        {% if user.is_authenticated %}
            <div class="text-warning bg-secondary text-center">
                VOCÊ JÁ ESTÁ LOGADO!
            </div>
        {% else %}
            <div class="row mt-4">
                <div class="col align-self-center text-center">
                    CRIE SEU LOGIN
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row my-2">
                    <div class="col">
                        <input
                                type="text"
                                name="txtUsername"
                                class="form-control"
                                placeholder="Informe o seu nome de usuário *"
                                required
                        >
                    </div>
                </div>
                <div class="row my-2">
                    <div class="col">
                        <input
                                type="password"
                                name="txtPassword"
                                class="form-control"
                                placeholder="Informe a sua senha *"
                                required
                        >
                    </div>
                </div>
                <div class="row my-2">
                    <div class="col">
                        <input
                                type="email"
                                name="txtEmail"
                                class="form-control"
                                placeholder="Informe o seu e-mail *"
                                required
                        >
                    </div>
                </div>
                <div class="row my-2">
                    <div class="col">
                        <input
                                type="text"
                                name="txtFirstName"
                                class="form-control"
                                placeholder="Informe o seu nome"
                        >
                    </div>
                </div>
                <div class="row my-2">
                    <div class="col">
                        <input
                                type="text"
                                name="txtLastName"
                                class="form-control"
                                placeholder="Informe o seu sobrenome"
                        >
                    </div>
                </div>
                <div class="row">
                    <div class="col d-flex justify-content-left">
                        <p style="font-size: 0.8em">Os campos com * são obrigatórios.</p>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col d-flex justify-content-center">
                        <button class="btn btn-primary" type="submit">Cadastrar</button>
                    </div>
                </div>
            </form>

        {% endif %}
    </div>
{% endblock %}

register/templates/register/success.html
{% extends 'base.html' %}

{% block content %}
<p>Usuário cadastrado com sucesso!<a href="{% url 'login' %}">Faça seu login</a></p>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Gestor de Finanças Pessoais</title>
  </head>
  <body>
  {% block content %}
    <h1>Hello, world!</h1>
  {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

users/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 480px">
        <div class="row mt-4">
            <div class="col align-self-center text-center">
                CADASTRE A SUA CONTA
            </div>
        </div>
        <form action="{% url 'users:create_account' %}" method="POST">
            {% csrf_token %}
            <div class="row my-2">
                <div class="col">
                    <input
                            type="text"
                            name="txtAccountName"
                            class="form-control"
                            placeholder="Informe o nome da conta"
                    >
                </div>
            </div>
            <div class="row my-2">
                <div class="col">
                    <input
                            type="number"
                            name="txtInitialBalance"
                            class="form-control"
                            value="0"
                            placeholder="Informe o saldo inicial da conta"
                    >
                </div>
            </div>
            <div class="row">
                <div class="col d-flex justify-content-left">
                    <p style="font-size: 0.8em">
                        <strong>IMPORTANTE:</strong> Apenas informe o saldo inicial se for uma conta bancária (corrente/poupança).
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <button class="btn btn-primary mb-2" type="submit">Criar sua conta</button>
                </div>
            </div>
        </form>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:index' %}">Voltar</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 550px">
        <div class="row">
            <div class="col text-center">
                <h2>Lista de contas</h2>
            </div>
        </div>
        <hr>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:create_account' %}">Criar nova conta</a>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:index' %}">Voltar</a>
            </div>
        </div>
        <div class="row mb-1">
            <div class="col text-center">
                <h4>Nome da conta</h4>
            </div>
            <div class="col text-center">
                <h4>Saldo</h4>
            </div>
        </div>
        {% for user_account in user_accounts %}
        <div class="row mb-2">
            <div class="col text-center">
                {{ user_account.name }}
            </div>
            <div class="col text-center">
                {{ user_account.balance }}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/profiles/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 480px">
        {% if not user.is_authenticated %}
            <h2 class="text-warning text-center">Você não está logado!</h2>
            <a href="{% url 'login' %}">Faça seu login!</a>
        {% else %}
            <h2 class="text-dark text-center">Olá, {{ user.username }}!</h2>
            <hr>
            <div class="row mt-2">
                <div class="col d-flex justify-content-center">
                    <h3>Dados do seu perfil</h3>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col d-flex justify-content-left">
                    <p>
                        <strong>Nome de usuário: </strong> {{ user.username }}
                    </p>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col d-flex justify-content-left">
                    <p>
                        <strong>Nome: </strong> {{ user.first_name }}
                    </p>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col d-flex justify-content-left">
                    <p>
                        <strong>Sobrenome: </strong> {{ user.last_name }}
                    </p>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col d-flex justify-content-left">
                    <p>
                        <strong>E-mail: </strong> {{ user.email }}
                    </p>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col d-flex justify-content-left">
                    <p>
                        <strong>Último login: </strong> {{ user.last_login }}
                    </p>
                </div>
            </div>
            <div class="row mt-2 mb-2">
                <div class="col d-flex justify-content-left">
                    <a href="{% url 'users:index' %}">Voltar</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

users/templates/transactions/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 480px">
        <div class="row mt-4">
            <div class="col align-self-center text-center">
                CADASTRE UMA NOVA TRANSAÇÃO
            </div>
        </div>

        <form action="{% url 'users:create_transaction' %}" method="POST">
            {% csrf_token %}

            <div class="row my-2">
                <div class="col d-flex justify-content-center">
                    Débito
                </div>
                <div class="col d-flex justify-content-center">
                    Crédito
                </div>
            </div>

            <div class="row my-2">
                <div class="col d-flex justify-content-center">
                    <select name="menuDebitAccount" id="menuDebitAccount">
                        {% for user_account in all_user_accounts %}
                            <option value="{{ user_account.id }}">{{ user_account.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col d-flex justify-content-center">
                    <select name="menuCreditAccount" id="menuCreditAccount">
                        {% for user_account in all_user_accounts %}
                            <option value="{{ user_account.id }}">{{ user_account.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row my-2">
                <div class="col">
                    <input
                            type="number"
                            name="txtValue"
                            class="form-control"
                            placeholder="Informe o valor da transação"
                            required
                    >
                </div>
            </div>
            <div class="row mb-2">
                <div class="col d-flex justify-content-center">
                    <button class="btn btn-primary" type="submit">Cadastrar</button>
                </div>
            </div>
        </form>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:index' %}">Voltar</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/transactions/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 980px">
        <h1 class="text-center">Lista de transações</h1>
        <hr>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:create_transaction' %}">Criar nova conta</a>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col">
                <a href="{% url 'users:index' %}">Voltar</a>
            </div>
        </div>
        {% for transaction in transactions %}
            <div class="row mb-4">
                <div class="col">
                    <strong>ID:</strong> {{ transaction.id }}
                </div>
                <div class="col">
                    <strong>Conta debitada:</strong> {{ transaction.debit_account.name }}
                </div>
                <div class="col">
                    <strong>Conta creditada:</strong> {{ transaction.credit_account.name }}
                </div>
                <div class="col">
                    <strong>Valor da transação:</strong> R$ {{ transaction.value }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>User detail</h1>
{% endblock %}

users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 700px">
        {% if not user.is_authenticated %}
        <div class="row">
            <div class="col justify-content-center">
                <h2 class="text-warning text-center">Você não está logado!</h2>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <a href="{% url 'login' %}">Faça seu login!</a>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col justify-content-center">
                <h2 class="text-dark text-center">Você está logado como {{ user.username }}.</h2>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <a href="{% url 'users:show_profile' %}">Acesse seu perfil!</a>
            </div>
        </div>
        <hr>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <p>
                        Você tem atualmente <strong>{{ total_num_accounts }}</strong> contas cadastradas.
                        {% if total_num_accounts == 0 %}
                            <a href="{% url 'users:create_account' %}">Cadastre a primeira</a>
                        {% else %}
                            <a href="{% url 'users:list_accounts' %}">Acesse a página de contas</a>
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <p class="mx-1">Você realizou um total de <strong>{{ total_num_transactions }}</strong> transações.</p>
                    {% if total_num_transactions == 0 %}
                        <a href="{% url 'users:create_transaction' %}">Cadastre a primeira transação</a>
                    {% else %}
                        <a href="{% url 'users:list_transactions' %}">Vá para a página de listagem de transações</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}